--- 
addons: 
  apt: 
    packages: 
      - libcurl4-openssl-dev
cache: bundler
env: 
  global: 
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
language: ruby
rvm: 
  - "2.4.1"
script: "bundle exec jekyll build"
sudo: false
